import { StyleSheet } from "react-native";
import { commonStyles, t, SPACING, RADIUS, FONT_SIZES } from "./styles.common";

export const overviewScreenStyles = StyleSheet.create({
  content: commonStyles.screenContent,
  header: { marginBottom: SPACING.xs },
  greeting: t.pageSub,
  title: t.pageTitle,
  heroCard: commonStyles.heroCard,
  heroLabel: t.heroLabel,
  heroTime: t.heroTime,
  heroSub: t.heroSub,
  row: { flexDirection: "row", gap: SPACING.md },
  section: commonStyles.section,
  sectionTitle: t.sectionTitle,
  empty: t.body,
  errorCard: {
    ...commonStyles.card,
    alignItems: "center",
    marginTop: SPACING.lg,
  },
  errorText: t.body,
});

export const historyScreenStyles = StyleSheet.create({
  content: commonStyles.screenContent,
  title: t.pageTitle,
  sub: { ...t.pageSub, marginBottom: SPACING.xs },
  list: { gap: SPACING.lg },
  card: { ...commonStyles.card, borderRadius: RADIUS.xl, gap: SPACING.md },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dayName: { fontSize: FONT_SIZES["2xl"], fontFamily: "Inter_600SemiBold" },
  dateStr: {
    fontSize: FONT_SIZES.sm,
    fontFamily: "Inter_400Regular",
    marginTop: SPACING.xs,
  },
  totalTime: t.value,
  barTrack: { height: 6, borderRadius: RADIUS.sm, overflow: "hidden" },
  barFill: { height: "100%", borderRadius: RADIUS.sm },
  tags: { flexDirection: "row", flexWrap: "wrap", gap: SPACING.sm },
  tag: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.md,
  },
  tagText: { fontSize: FONT_SIZES.sm, fontFamily: "Inter_500Medium" },
  error: t.body,
});

export const breakdownScreenStyles = StyleSheet.create({
  content: commonStyles.screenContent,
  title: t.pageTitle,
  pills: { flexDirection: "row", gap: SPACING.md },
  pill: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.full,
    borderWidth: 1,
  },
  pillText: { fontSize: FONT_SIZES.md, fontFamily: "Inter_500Medium" },
  
 
  summaryRow: { flexDirection: "row", gap: SPACING.lg },
  summaryItem: {
    flex: 1,
    borderRadius: RADIUS.lg,
    padding: SPACING.lg - 2,
    borderWidth: 1,
    gap: SPACING.xs,
  },
  summaryLabel: t.label,
  summaryValue: { fontSize: FONT_SIZES.xl, fontFamily: "Inter_700Bold" },
  catRow: { flexDirection: "row", flexWrap: "wrap", gap: SPACING.md },
  catBtn: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs + 2,
    borderRadius: RADIUS.full,
    borderWidth: 1,
  },
  catText: { fontSize: FONT_SIZES.md, fontFamily: "Inter_500Medium" },
  card: { ...commonStyles.section },
  keyRow: { flexDirection: "row", alignItems: "center", gap: SPACING.sm },
  keyDot: { width: 8, height: 8, borderRadius: 4 },
  keyText: { flex: 1, fontSize: FONT_SIZES.md, fontFamily: "Inter_500Medium" },
  empty: t.body,
  error: t.body,
});

export const settingsScreenStyles = StyleSheet.create({
  content: commonStyles.screenContent,
  title: t.pageTitle,
  profileCard: {
    ...commonStyles.card,
    borderRadius: RADIUS.xl,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.lg - 2,
  },
  avatar: { width: 60, height: 60, borderRadius: 30 },
  avatarFallback: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  profileInfo: { flex: 1, gap: SPACING.xs },
  displayName: { fontSize: FONT_SIZES["2xl"], fontFamily: "Inter_600SemiBold" },
  username: t.body,
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    marginTop: SPACING.xs,
  },
  location: { fontSize: FONT_SIZES.sm, fontFamily: "Inter_400Regular" },
  section: { ...commonStyles.card, borderRadius: RADIUS.xl, gap: SPACING.md },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
  },
  sectionTitle: {
    fontSize: FONT_SIZES.base,
    fontFamily: "Inter_600SemiBold",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  sectionDesc: { ...t.body, lineHeight: 18, marginTop: -SPACING.xs },
  keyRow: { flexDirection: "row", alignItems: "center", gap: SPACING.sm },
  keyText: { flex: 1, fontSize: FONT_SIZES.md, fontFamily: "Inter_500Medium" },
  inputRow: {
    ...commonStyles.inputRow,
    height: 48,
    borderRadius: RADIUS.lg - 2,
  },
  input: { flex: 1, fontSize: FONT_SIZES.md },
  btnRow: { flexDirection: "row", gap: SPACING.md },
  cancelBtn: {
    flex: 1,
    height: 44,
    borderRadius: RADIUS.lg - 2,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelText: { fontSize: FONT_SIZES.md, fontFamily: "Inter_500Medium" },
  saveBtn: {
    flex: 2,
    height: 44,
    borderRadius: RADIUS.lg - 2,
    alignItems: "center",
    justifyContent: "center",
  },
  saveText: { fontSize: FONT_SIZES.md, fontFamily: "Inter_600SemiBold" },
  editBtn: { padding: SPACING.md, borderRadius: RADIUS.md },
  editSection: { gap: SPACING.lg - 6 },
});

export const setupScreenStyles = StyleSheet.create({
  container: { paddingHorizontal: SPACING.xl + 4, gap: SPACING.lg },
  iconWrap: { alignSelf: "center", marginBottom: SPACING.md },
  title: {
    fontSize: FONT_SIZES["8xl"],
    fontFamily: "Inter_700Bold",
    textAlign: "center",
    letterSpacing: -1,
  },
  sub: {
    ...t.pageSub,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: SPACING.md,
  },
  inputRow: { ...commonStyles.inputRow },
  input: commonStyles.input,
  eyeBtn: { padding: SPACING.sm },
  error: { ...t.body, textAlign: "center" },
});
